on: [push, pull_request]

name: deploy-shiny

jobs:
  deploy-shiny:
    runs-on: windows-latest
    env:
      shiny_name: ${{ secrets.SHINYAPPS_NAME }}
      shiny_token: ${{ secrets.SHINYAPPS_TOKEN }}
      shiny_secret: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install shiny
        run: |
          install.packages(c("shiny", "rsconnect"), type = "binary")
        shell: Rscript {0}
      - name: Deploy
        run: |
          rsconnect::setAccountInfo(
            name = Sys.getenv('shiny_name'),
            token = Sys.getenv('shiny_token'),
            secret = Sys.getenv('shiny_secret'))
          rsconnect::deployApp(appName = 'shiny_actions_test')
        shell: Rscript {0}